### PR TITLE
Add CI category to release-drafter

### PR DESCRIPTION
**Pull request by oddstr13**

### CODE REVIEW

**Review by h1dden-da3m0n — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Comment by h1dden-da3m0n** [comment]
Sidennote: Juts in case the Jellyfin org wants to use RD more I would advice creating and using a `jellyfin/.github` repository where you can hold a general RD template (as well as Issue and PR templates) that you then only need to customize in the different repos that want to use it. (just FYI and feel free to give me a shout if you think I can help in any way)

**Comment by oddstr13** [comment]
@h1dden-da3m0n I'd love more details on how that would work.
Would we put the files in that repo, and enable them in some way on each repo that wants to use it? (by overwriting triggers or some such?)

cc @jellyfin/core

**Comment by h1dden-da3m0n** [comment]
Well, to be 100% transparent here I did mention this quite a while back in the Matrix chat. depending on that you want to do with that repo, but here the official [github/.github](https://github.com/github/.github), [docu](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file) and the ["example"](https://github.com/jenkinsci/.github) I have the original idea from, as well as the RD information.

If you need any further info it would be my pleasure to provide it :wink:

**Comment by oddstr13** [comment]
Right, so this is explicit support in release-drafter, not generic support for pipelines across all repos.

Would still make sense to set up release drafter template for plugins.
Maybe in the jellyfin-plugin-meta repo? Right now it's just (always out of date) list of submodules pointing to (many of) the plugin repos.

**Comment by h1dden-da3m0n** [comment]
Unfortunately, the `.github` repo is only for community files such as Issue templates, Contributing guidelines etc. AFAIK (I manly knew of it due to RD and my contributions to various Jenkins plugins)
Yes the `jellyfin-plugin-meta` sounds like a good choice :+1: (I will open a PR tomorrow for that if that is fine)

**Comment by h1dden-da3m0n** [comment]
Okay done, I hope I did not mess up :sweat_smile:

**Comment by h1dden-da3m0n** [comment]
btw I stumbled over this (seemingly at random xD) [Sharing workflows with your organization](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/sharing-workflows-with-your-organization)

**Review by crobibero — APPROVED** [review]

**Comment by oddstr13** [comment]
Superseeded by jellyfin/jellyfin-meta-plugins#3 and #75

**Pull request closed without merging**
