### PR TITLE
ChangePassword implementation

### PR DESCRIPTION
**Pull request by alanbaumgartner**
### Disclaimer

I am a Java dev so I don't know c# best practices and I am also very unfamiliar with ldap in general, but I wanted this feature for mine own server so I whipped this up really quick, its likely not super great but feel free to suggest changes. I tested it for my server and it worked correctly but it may not depending on different ldap settings (As I said, I don't know much about it).

Changes that could be made are to add a constant variable for the "userPassword" field. I also think it would be beneficial to not repeat the same code in every function for creating an ldap connection but I didn't add that to this PR.

let me know if there are changes I should make.

### CODE REVIEW

**Review by joshuaboniface — APPROVED** [review]
Sorry for the delays, looks good! Assuming this was tested and working.

One thing we'd like is the ability to enable or disable this explicitly in the plugin config. In my instance forever I do not want to grant users this ability (they have a page for that), etc.

**Review by joshuaboniface — CHANGES_REQUESTED** [review]
Clicked the wrong button...

**Comment by oddstr13** [comment]
Just to clarify, this PR is pending a option in the plugin settings to enable/disable this feature.

**Comment by alanbaumgartner** [comment]
Got it, busy weeks at work so I haven't had time to come back and update.

**Comment by oddstr13** [comment]
No worries, I just clearly pointed out the reason this wasn't getting reviewed / merged yet :slightly_smiling_face:

**Pull request merged**
